### ISSUE TITLE
Pop-up is too low on Android

### ISSUE THREAD

**Issue by rpander93** [carsonwah/react-native-push-notification-popup#35]
Hi there,

We found that the pop-up is too low on Android if not using the translucent statusbar. In our case, we switched from managing the statusbar with the <StatusBar /> component to letting Android manage it. We then saw that the pop-up was rendered with a top margin of approx. 1x the height of the statusbar. This is caused by: 
https://github.com/carsonwah/react-native-push-notification-popup/blob/614575e7ca9254450f806457d1a306db342daa1b/src/views/DefaultPopup.js#L14
Setting this to 0 manually fixes the issue. Unfortunately it seems that this is not configurable, so we had do copy the whole file just to make this adjustment. Is this something that could be fixed?

**Comment by carsonwah** [comment]
@rpander93  Sorry for the late reply. Oh I overlooked this.
This is because if StatusBar is not translucent, the whole app will be rendered starting at the bottom of the StatusBar.

So the correct height should be:
- iOS with notch: 44
- iOS without notch: 20
- Android with translucent StatusBar: StatusBar.currentHeight + 10
- Android with non-translucent StatusBar: 10

Seems there is no way to determine in code whether StatusBar is translucent or not. I will opt for externalizing it as props. Will find a time to implement this. Thanks for reporting and sorry for the inconvenience caused.

**Comment by rpander93** [comment]
No worries! That's indeed what's going on. Thanks for looking into it.

**Comment by NxsHbb** [comment]
Any update!

**Comment by carsonwah** [comment]
Fixed in v1.7.0.
https://www.npmjs.com/package/react-native-push-notification-popup/v/1.7.0
